### ISSUE TITLE
Helixer fails on some plant genomes

### ISSUE THREAD

**Issue by aubombarely** [weberlab-hhu/Helixer#170]
**Describe the bug**
The Helixer program does not produce a GFF file with certain genome assemblies. It runs well with many assemblies from NCBI, Phytozome or produced in house, but it fails with some others like the Nicotiana attenuata genome (GCA_030864195.1 downloaded from NCBI). It is not related with the assembly size or number of scaffolds. This assembly has size of 2.2 Gb and it has 1,311 contigs, but we have annotated larger genomes (e.g., 10.48 Gb with 924 contigs or 9.87 Gb with 242,858 contigs). It has standard nucleotide composition (ATGCN). This failure is reproducible (if the same command is run, it fails in the same step). It has failed in three genomes of more than 100 plant genomes that I have run.

**To Reproduce**

```
## 1. Download the genome assembly from NCBI 
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/030/864/195/GCA_030864195.1_Niat.v3/GCA_030864195.1_Niat.v3_genomic.fna.gz

## 2. Change the sequence names
perl -ne 'chomp($_); if ($_ =~ m/>.+UT31x chromosome (\d+),/) { $id="NiattUT31xV3C".sprintf("%02s", $1); print ">$id\n"} elsif ($_ =~ m/>.+UT31x scaffold(\d+),/) { $id="NiattUT31xV3S".$1; print ">$id\n" } else { print "$_\n"}' GCA_030864195.1_Niat.v3_genomic.fna > Nicotiana_attenuata_UT31xV3_GCA_030864195.fasta

## 3. Run Helixer with singularity (COMMAND THAT PRODUCE THE ERROR)
singularity run --nv helixer-docker_helixer_v0.3.3_cuda_11.8.0-cudnn8.sif Helixer.py --fasta-path Nicotiana_attenuata_UT31xV3_GCA_030864195.fasta --lineage land_plant --gff-output-path Nicotiana_attenuata_UT31xV3_GCA_030864195.helixer.gff3
```

**Error**
The command line output including the error thrown.

`
2025-01-28 11:30:11.766089: W tensorflow/core/framework/op_kernel.cc:1828] OP_REQUIRES failed at cudnn_rnn_ops.cc:1769 : UNKNOWN: CUDNN_STATUS_BAD_PARAM
in tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc(1688): 'cudnnSetTensorNdDescriptor( tensor_desc.get(), data_type, sizeof(dims) / sizeof(dims[0]), dims, stride
s)'
2025-01-28 11:30:11.766205: W tensorflow/core/framework/op_kernel.cc:1828] OP_REQUIRES failed at cudnn_rnn_ops.cc:1769 : UNKNOWN: CUDNN_STATUS_BAD_PARAM
in tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc(1688): 'cudnnSetTensorNdDescriptor( tensor_desc.get(), data_type, sizeof(dims) / sizeof(dims[0]), dims, stride
s)'
2025-01-28 11:30:11.766862: I tensorflow/core/framework/local_rendezvous.cc:405] Local rendezvous recv item cancelled. Key hash: 6433283459957011054
2025-01-28 11:30:11.766891: I tensorflow/core/framework/local_rendezvous.cc:405] Local rendezvous recv item cancelled. Key hash: 13939088232644917226
2025-01-28 11:30:11.766910: I tensorflow/core/framework/local_rendezvous.cc:405] Local rendezvous recv item cancelled. Key hash: 16633559319466144975
2025-01-28 11:30:11.766937: I tensorflow/core/framework/local_rendezvous.cc:405] Local rendezvous recv item cancelled. Key hash: 4080324063042680119
2025-01-28 11:30:11.766956: I tensorflow/core/framework/local_rendezvous.cc:405] Local rendezvous recv item cancelled. Key hash: 3662181050547821255
2025-01-28 11:30:11.766977: I tensorflow/core/framework/local_rendezvous.cc:405] Local rendezvous recv item cancelled. Key hash: 15422924683898961819
2025-01-28 11:30:11.767023: I tensorflow/core/framework/local_rendezvous.cc:405] Local rendezvous recv item cancelled. Key hash: 9335587239357735921
2025-01-28 11:30:11.767044: I tensorflow/core/framework/local_rendezvous.cc:405] Local rendezvous recv item cancelled. Key hash: 7746153079705547965
2025-01-28 11:30:11.767069: I tensorflow/core/framework/local_rendezvous.cc:405] Local rendezvous recv item cancelled. Key hash: 17385428655836925301
2025-01-28 11:30:11.767087: I tensorflow/core/framework/local_rendezvous.cc:405] Local rendezvous recv item cancelled. Key hash: 4168280406221745445
2025-01-28 11:30:11.767106: I tensorflow/core/framework/local_rendezvous.cc:405] Local rendezvous recv item cancelled. Key hash: 10325243409860886744
2025-01-28 11:30:11.767124: I tensorflow/core/framework/local_rendezvous.cc:405] Local rendezvous recv item cancelled. Key hash: 5309230069943092584
2025-01-28 11:30:11.767148: I tensorflow/core/framework/local_rendezvous.cc:405] Local rendezvous recv item cancelled. Key hash: 4232506014939487252
2025-01-28 11:30:11.767167: I tensorflow/core/framework/local_rendezvous.cc:405] Local rendezvous recv item cancelled. Key hash: 9047112709641948480
2025-01-28 11:30:11.767187: I tensorflow/core/framework/local_rendezvous.cc:405] Local rendezvous recv item cancelled. Key hash: 9336422959862537824
ESC[31mErrors at prediction often result from exhausting the GPU RAM.Your RAM requirement depends on subsequence_length x (val_test_)batch_size.That and the network size (can be changed during training but not inference).ESC[0m
Traceback (most recent call last):
  File "/usr/local/bin/Helixer.py", line 248, in <module>
    main()
  File "/usr/local/bin/Helixer.py", line 228, in main
    model.run()
  File "/usr/local/lib/python3.8/dist-packages/helixer/prediction/HelixerModel.py", line 1031, in run
    self._make_predictions(model)
  File "/usr/local/lib/python3.8/dist-packages/helixer/prediction/HelixerModel.py", line 845, in _make_predictions
    raise e
  File "/usr/local/lib/python3.8/dist-packages/helixer/prediction/HelixerModel.py", line 839, in _make_predictions
    predictions = model.predict_on_batch(input_data)
  File "/usr/local/lib/python3.8/dist-packages/keras/src/engine/training.py", line 2777, in predict_on_batch
    outputs = self.predict_function(iterator)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/execute.py", line 53, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.CancelledError: Graph execution error:

RecvAsync is cancelled.
         [[{{node model/genic/Softmax/_59}}]] [Op:__inference_predict_function_14318]
`

**Expected behavior**
The expected behaviour is that it should produce a GFF. For assemblies in which this has been working, the message "Neural network prediction done. Starting post processing" appears. When it fails, do it before this step.

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04.5 LTS
 - Singularity version 3.8.6
 - Singularity container helixer-docker_helixer_v0.3.3_cuda_11.8.0-cudnn8.sif
 - CUDA Version 11.8.0

**Additional context**

**Comment by felicitas215** [comment]
Hi, thanks for raising this issue. Your error message looks like a bug some people encountered in tensorflow 2.13.1. When trying to reproduce your example with the newest version of our singularity image, which uses tensorflow 2.15.1, everything works. Could you try annotating _Nicotiana attenuata_ using the new image? You can download it with this command `singularity pull  docker://gglyptodon/helixer-docker:helixer_v0.3.4_cuda_12.2.2-cudnn8`.

**Comment by aubombarely** [comment]
Dear @felicitas215 thanks for the answer. I have downloaded the image, as you recommended, but I still have the same problem.

I got the following error:
=====
Errors at prediction often result from exhausting the GPU RAM.Your RAM requirement depends on subsequence_length x (val_test_)batch_size.That and the network size (can be changed during training but not inference).
Traceback (most recent call last):
  File "/usr/local/bin/Helixer.py", line 267, in <module>
    main()
  File "/usr/local/bin/Helixer.py", line 247, in main
    model.run()
  File "/usr/local/lib/python3.10/dist-packages/helixer/prediction/HelixerModel.py", line 1046, in run
    self._make_predictions(model)
  File "/usr/local/lib/python3.10/dist-packages/helixer/prediction/HelixerModel.py", line 860, in _make_predictions
    raise e
  File "/usr/local/lib/python3.10/dist-packages/helixer/prediction/HelixerModel.py", line 854, in _make_predictions
    predictions = model.predict_on_batch(input_data)
  File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 2880, in predict_on_batch
    outputs = self.predict_function(iterator)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/eager/execute.py", line 53, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnknownError: Graph execution error:

Detected at node CudnnRNN defined at (most recent call last):
<stack traces unavailable>
Detected at node CudnnRNN defined at (most recent call last):
<stack traces unavailable>
Detected at node CudnnRNN defined at (most recent call last):
<stack traces unavailable>
3 root error(s) found.
  (0) UNKNOWN:    CUDNN_STATUS_BAD_PARAM
in external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc(1746): 'cudnnSetTensorNdDescriptor( tensor_desc.get(), data_type, sizeof(dims) / sizeof(dims[0]), dims, strides)'
	 [[{{node CudnnRNN}}]]
	 [[replica_2/model/bidirectional/forward_lstm/PartitionedCall]]
	 [[replica_1/model/phase/Softmax/_66]]
	 [[model/genic/Softmax/_51]]
  (1) UNKNOWN:    CUDNN_STATUS_BAD_PARAM
in external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc(1746): 'cudnnSetTensorNdDescriptor( tensor_desc.get(), data_type, sizeof(dims) / sizeof(dims[0]), dims, strides)'
	 [[{{node CudnnRNN}}]]
	 [[replica_2/model/bidirectional/forward_lstm/PartitionedCall]]
	 [[replica_1/model/phase/Softmax/_66]]
  (2) UNKNOWN:    CUDNN_STATUS_BAD_PARAM
in external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc(1746): 'cudnnSetTensorNdDescriptor( tensor_desc.get(), data_type, sizeof(dims) / sizeof(dims[0]), dims, strides)'
	 [[{{node CudnnRNN}}]]
	 [[replica_2/model/bidirectional/forward_lstm/PartitionedCall]]
0 successful operations.
0 derived errors ignored. [Op:__inference_predict_function_14318]
INFO:    Cleaning up image...
====
 I am using three GPU NVIDIA Tesla T4 75W with 16 Gb of RAM each. During the first part of the process, they were running fine, using between 2 and 4 Gb of RAM of the each GPU.

**Comment by felicitas215** [comment]
I don't think we explicitly state it, but our code assumes inference is run on one GPU only. Could you try one GPU and see if the error persists? That seems to be the only difference between our setups.

**Comment by aubombarely** [comment]
Thanks. I'll try that. Do you know how can I change the gpu-id for Helixer.py? I saw the option for HybridModel.py but I didn't see it for Helixer.py or the config file.

**Comment by felicitas215** [comment]
Do you use a job scheduling system like PBS or Sun Grid Engine? If yes, you don't need to set one, just request one GPU. Otherwise you can set the GPU via an environment variable: `singularity exec --nv helixer-docker_helixer_v0.3.4_cuda_12.2.2-cudnn8.sif bash -c 'export CUDA_VISIBLE_DEVICES=0; Helixer.py --fasta-path Nicotiana_attenuata_UT31xV3_GCA_030864195.fasta --lineage land_plant --gff-output-path 2Nicotiana_attenuata_UT31xV3_GCA_030864195.helixer.gff3'`. This will use the GPU with the ID 0.

**Comment by aubombarely** [comment]
I am using a simple node, no PBS. I followed your suggestion of lower the batch and it worked fine (--batch-size 16 if someone has the same problem). I didn't need to use only one GPU. Thank you for your help. By the way, big fan of the tool.

**Comment by felicitas215** [comment]
Ah, so the culprit was the GPU running out of memory after all. I'm glad it works now.
And thank you for being a fan :).
